[ticker.convert]
fiat = [
    "USD",
    "EUR",
    "GBP",
    "RUB",
    "JPY",
    "CAD",
    "KRW",
    "PLN"
]
crypto = [
    "BTC",
    "ETH",
    "XRP",
    "LTC",
    "BCH"
]

[ticker]
structure = [
    "dictionary",
    "array"
]

[fng]
format = [
    "json",
    "csv"
]

date_format = [
    "us",
    "cn",
    "kr",
    "world"
]