stock = [
    'Apple,AAPL',
    'Microsoft,MSFT',
    'Alphabet,GOOG',
    'Amazon,AMZN',
    'Tesla,TSLA',
    'Berkshire Hathaway,BRK-B',
    'Meta Platforms,META',
    'Visa,V',
    'NVIDIA,NVDA',
    'Walmart,WMT',
    'JPMorgan Chase,JPM',
    'Mastercard,MA',
    'Bank of America,BAC',
    'Gamestop,GME',
    'AMC,AMC',
    'Coca-Cola,KO',
    'Wells Fargo,WFC',
    'Intel,INTC',
    'Texas Instruments,TXN',
    'AMD,AMD',
    'AT&T,T',
    'Ford,F',
    'General Motors,GM'
]

crypto = [
    'Bitcoin,BTC',
    'Ethereum,ETH',
    'Binance Coin,BNB',
    'XRP,XRP',
    'Cardano,ADA',
    'Solana,SOL',
    'Dogecoin,DOGE',
    'Polkadot,DOT',
    'Avalance,AVAX',
    'Shiba Inu,SHIB',
    'Tron,TRX',
    'Uniswap,UNI',
    'Litecoin,LTC',
    'Chainlink,LINK',
    'Monero,XMR',
    'Bitcoin Cash,BCH'
]