[units]
"seconds" = [
    "s",
    "sec",
    "second"
]
"minutes" = [
    "m",
    "min",
    "minute"
]
"hours" = [
    "h",
    "hour"
]
"days" = [
    "d",
    "day"
]
"weeks" = [
    "w",
    "wk",
    "week",
    "week"
]
"months" = [
    "mo",
    "mon",
    "month"
]
"years" = [
    "y",
    "yr",
    "year"
]