"data/[id]" = [
    "id",
    "name",
    "symbol",
    "website_slug",
    "rank",
    "circulating_supply",
    "total_supply",
    "max_supply",
    "last_updated"
]

"data/[id]/quotes/[convert]" = [
    "price",
    "volume_24h",
    "market_cap",
    "percentage_change_1h",
    "percentage_change_24h",
    "percentage_change_7d",
    "percent_change_1h",
    "percent_change_24h",
    "percent_change_7d"
]

"metadata" = [
    "timestamp",
    "num_cryptocurrencies"
]